### PR TITLE
Convert templates to YAML

### PR DESCRIPTION
**Pull request by gliptak**
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by gliptak** [comment]
@sshvans please review

**Comment by sshvans** [comment]
@gliptak Have you tested the updated templates using [TaskCat](https://github.com/aws-quickstart/taskcat), cloudformation testing tool? 
It failed in our testing after I merged this PR and therefore it's not promoted to master branch. 
Please send me the TaskCat success report after you have tested the templates.

**Comment by gliptak** [comment]
@sshvans I recall validating in the ```Console```. Thank you for the pointer, I will check with ```taskcat```.

**Comment by gliptak** [comment]
@sshvans ```taskcat --lint``` fails on the JSON templates

```
$ taskcat --lint -c ci/taskcat.yml
 _            _             _
| |_ __ _ ___| | _____ __ _| |_
| __/ _` / __| |/ / __/ _` | __|
| || (_| \__ \   < (_| (_| | |_
 \__\__,_|___/_|\_\___\__,_|\__|

[taskcat] :AWS AccountNumber:    [zzzz]
[taskcat] :Authenticated via:    [environment]


[taskcat] :Reading Config from: ci/taskcat.yml
[taskcat] |Queing test => splunk-enterprise
[ERROR  ] :Linter failed to load template /home/ec2-user/quickstart-splunk-enterprise/templates/splunk-enterprise.template "found character '\t' that cannot start any token" line 1360, column 0
[ERROR  ] :Lint detected issues for test splunk-enterprise on template /home/ec2-user/quickstart-splunk-enterprise/templates/splunk-enterprise-master.template:
[INFO   ] :    line 163 [W2001] [Check if Parameters are Used] (Parameter SplunkSearchHeadDiskSize not used.)
[INFO   ] :    line 189 [W2001] [Check if Parameters are Used] (Parameter SplunkSearchFactor not used.)
[INFO   ] :Linting completed
```

How would you like to handle this? Patch JSON first or resubmit YAML?

**Comment by sshvans** [comment]
@gliptak I was able to successsfully launch the template using taskcat. But, the stack creation failed with the following error:

`2019-09-17 01:33:55.413000+00:00  CREATE_FAILED       AWS::CloudFormation::Stack                tcat-qs-ci-splunk-enterprise-609dd98a-SplunkStack-TTNGI89AXEX5  Stack creation time exceeded the specified timeout
2019-09-17 01:33:54.882000+00:00  CREATE_FAILED       AWS::EC2::Instance                        SplunkCM                                                        Resource creation cancelled`

So, something is wrong with the splunk setup in EC2 instance, which is taking longer and causing timeout. The JSON templates were passing successfully in our CI.

**Pull request merged**
